models:

- id: gpt5nano
  name: 'GPT-5 Nano'
  provider: 'OpenAI'
  provider_model_name: 'gpt-5-nano'
    
  settings:
    n_retries: 5
    retry_delay: 1

- id: gpt4
  name: 'GPT-4.1'
  provider: 'OpenAI'
  provider_model_name: 'gpt-4.1'
    
  settings:
    n_retries: 5
    retry_delay: 1

- id: gpt4nano
  name: 'GPT-4.1 Nano'
  provider: 'OpenAI'
  provider_model_name: 'gpt-4.1-nano'
    
  settings:
    n_retries: 5
    retry_delay: 1

- id: gpt4mini
  name: 'GPT-4.1 Mini'
  provider: 'OpenAI'
  provider_model_name: 'gpt-4.1-mini'

  params:
    temperature: 0.8
    top_p: 1.0
    max_tokens: 1024
    
  settings:
    n_retries: 5
    retry_delay: 1

- id: gpt4o
  name: 'GPT-4o'
  provider: 'OpenAI'
  provider_model_name: 'gpt-4o'
    
  settings:
    n_retries: 5
    retry_delay: 1

- id: gpt4omini
  name: 'GPT-4o Mini'
  provider: 'OpenAI'
  provider_model_name: 'gpt-4o-mini'
    
  settings:
    n_retries: 5
    retry_delay: 1
